remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Lab 5
description: Throughout this lab we had to download and install Postman. We learned to nagivate the program and used it to test server GET routes. We also used POST request. 
